Add instructions for closing a Mango Account
blockworks-foundation/mango-v3 pull request #73
Opened 2021-10-26 23:30 UTC by riordanp

Devnet test is on a branch of the same name on the client. I may have missed some necessary preconditions in `close_mango_account`

2021-11-01 17:46 UTC, dafyddd requested changes

2021-11-02 13:38 UTC, riordanp commented on program/src/processor.rs
> +            check_eq!(mango_account.deposits[i], ZERO_I80F48, MangoErrorCode::InvalidAccountState)?;
Planning to just withdraw all dust with UI code before calling this for the moment

2021-11-02 13:40 UTC, riordanp commented on program/src/processor.rs
> +            check!(perp_account.is_liquidatable(), MangoErrorCode::InvalidAccountState)?;
I think the is_liquidatable check actually ensures all orders are cancelled and taker base & quote are zero, was named for use in the liquidation functions but it's repurposed here. Could rename to something more general like `has_no_open_orders`.

I don't think a liquidation check in terms of account health is needed as there are already checks for open positions and borrows

2021-11-02 15:17 UTC, dafyddd commented on program/src/processor.rs
> +        check!(&mango_account.owner == owner_ai.key, MangoErrorCode::InvalidOwner)?;
need to check owner is signer

2021-12-06 21:32 UTC, merged